= SymetryML REST API Reference Manual
:toc:
:toclevels: 1
:toc-placement: preamble
:doctype: book
:imagesdir: ./media/rest
:sectnums:

Copyright © 2020 by Symetry, Inc. +
14 Pine Street, Ste 6 +
Morristown, NJ 07960 +
All Rights Reserved +
Nov. 30th, 2020


[[about-timeseries-expansion]]
=== About Time Series Expansion

Its possible to add additional features as lag of a basic features. 
TBD

[[automl]]
== AutoML with SymetryML

TODO: Add transform after auto ml





[[select-model]]
== Select Model with SymetryML


[[select-model-df-api]]
=== Select Model Rest API

Allows to invoke the 'select model' functionality by specifying an external data source id.

==== URL
....
POST /symetry/rest/{cid}/projects/{pid}/selectModel/{dsid} [body=MLContext]
....

[[select-model-query-parameters]]
==== Query Parameters

[width="100%", cols="<25%,<25%,<50%",options="header",]
|=============================
| Parameter |Required/Optional? |Description
| modelid |Required | ID to assign to the new model.
| algo | Required | Algorithm to fit
|=============================

[[select-model-build-parameters]]
==== MLContext Build Parameters


[width="100%", cols="<20%,<20%,<20%,<40%",options="header",]
|=============================
| Parameter | Required/Optional?  | Type | Description
| *rnd_seed* | Optional | Integer | Set the seed of the randomizer
| *selector_type* | Optional | String |Default is *selector_type_fw_bw*
| *autoselect_grid_type* | Optional | String | Default is *autoselect_grid_type_tiny*
|=============================

[[select-model-response]]
==== HTTP Responses

[width="100%", cols="<25%,<25%,<50%",options="header",]
|=============================
|HTTP Status Code |HTTP Status Message |Description
|202 | OK | Job accepted.
|400 | BAD REQUEST | Unknown SymetryML project.
`{"statusCode":"BAD_REQUEST","statusString":" +
Cannot Find SYMETRYML id[r2] for Customer id [c1]","values":{}}`
|=============================

[[select-model-example]]
==== Sample Request Response Classifier

....
Request:
POST url="/symetry/rest/c1/projects/p1/selectModel/Iris_rtlm.csv?algo=lda&modelid=lda1

Body:
{
    "targets":[],
    "inputAttributes":[],
    "inputAttributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
    "targetAttributeNames":["Iris_virginica"],
    "extraParameters":{"rnd_seed":"1"}
}
....

[[select-model-example-2]]
==== Sample Request Response Regression

....
Request:
POST url="/symetry/rest/c1/projects/p1/selectModel/Iris_rtlm.csv?algo=mlr&modelid=mlr1

Body:
{
    "targets":[],
    "inputAttributes":[],
    "inputAttributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
    "targetAttributeNames":["sepal_length"],
    "extraParameters":{"rnd_seed":"1"}}

}
....












[[select-model-df-api]]
=== Select Model Dataframe Rest API

Allows to invoke the 'select model' functionality by using a <<dataframe-json>> passed in the request body.

==== URL
....
POST /symetry/rest/{cid}/projects/{pid}/selectModel [body=Map{"dataframe"=DataFrame, "mlcontext"=MLContext}]
....

[[select-model-df-query-parameters]]
==== Query Parameters

[width="100%", cols="<25%,<25%,<50%",options="header",]
|=============================
| Parameter |Required/Optional? |Description
| modelid |Required | ID to assign to the new model.
| algo | Required | Algorithm to fit
|=============================

[[select-model-df-build-parameters]]
==== MLContext Build Parameters


[width="100%", cols="<20%,<20%,<20%,<40%",options="header",]
|=============================
| Parameter | Required/Optional?  | Type | Description
| *rnd_seed* | Optional | Integer | Set the seed of the randomizer
| *selector_type* | Optional | String |Default is *selector_type_fw_bw*
| *autoselect_grid_type* | Optional | String | Default is *autoselect_grid_type_tiny*
|=============================

[[select-model-df-response]]
==== HTTP Responses

[width="100%", cols="<25%,<25%,<50%",options="header",]
|=============================
|HTTP Status Code |HTTP Status Message |Description
|202 | OK | Job accepted.
|400 | BAD REQUEST | Unknown SymetryML project.
`{"statusCode":"BAD_REQUEST","statusString":" +
Cannot Find SYMETRYML id[r2] for Customer id [c1]","values":{}}`
|=============================

[[select-model-df-example]]
==== Sample Request Response Classifier

....
Request:
POST url="/symetry/rest/c1/projects/p1/selectModel?algo=lda&modelid=lda1

Body:
{
    "mlcontext" : {
        "targets":[],
        "inputAttributes":[],
        "inputAttributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
        "targetAttributeNames":["Iris_virginica"],
        "extraParameters":{"rnd_seed":"1"}}
    "dataframe" : {
        "attributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
        "attributeTypes":["C","C","C","C","B","B","B","B","B","B","B","B","B","B","B"]
        "data":[
            ["4.3","3","1.1","0.1","1","0","0","1","1","0","1","0","1","0","0"],
            ["4.8","3","1.4","0.1","1","0","0","1","1","0","1","0","1","0","0"],
            ["4.9","3.1","1.5","0.1","1","0","0","1","1","0","1","0","1","0","0"]
            (...)
            ["7.2","3.6","6.1","2.5","0","1","0","1","0","1","0","1","0","0","1"]
        ],

    }

}
....

[[select-model-df-example-2]]
==== Sample Request Response Regression

....
Request:
POST url="/symetry/rest/c1/projects/p1/selectModel?algo=mlr&modelid=mlr1

Body:
{
    "mlcontext" : {
        "targets":[],
        "inputAttributes":[],
        "inputAttributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
        "targetAttributeNames":["sepal_length"],
        "extraParameters":{"rnd_seed":"1"}}
    "dataframe" : {
        "attributeNames":["sepal_length","sepal_width","petal_length","petal_width","sepal_lengt_b1","sepal_lengt_b2","sepal_width_b1","sepal_width_b2","petal_length_b1","petal_length_b2","petal_width_b1","petal_width_b2","Iris_setosa","Iris_versicolor","Iris_virginica"],
        "attributeTypes":["C","C","C","C","B","B","B","B","B","B","B","B","B","B","B"]
        "data":[
            ["4.3","3","1.1","0.1","1","0","0","1","1","0","1","0","1","0","0"],
            ["4.8","3","1.4","0.1","1","0","0","1","1","0","1","0","1","0","0"],
            ["4.9","3.1","1.5","0.1","1","0","0","1","1","0","1","0","1","0","0"]
            (...)
            ["7.2","3.6","6.1","2.5","0","1","0","1","0","1","0","1","0","0","1"]
        ],

    }
}
....









[[auto-select]]
== Auto Select with SymetryML


